// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQcc7CYIx3LSXG9Taf1COmrKxa5Njv04',
    appId: '1:998569864600:web:c060d5a9ab444c011c8fed',
    messagingSenderId: '998569864600',
    projectId: 'biddingapp-2b035',
    authDomain: 'biddingapp-2b035.firebaseapp.com',
    storageBucket: 'biddingapp-2b035.firebasestorage.app',
    measurementId: 'G-QSGRREZMN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Ve9XmZSBNykZDiSLYfB3IkOvv3h6IZo',
    appId: '1:998569864600:android:542619897b8eedcd1c8fed',
    messagingSenderId: '998569864600',
    projectId: 'biddingapp-2b035',
    storageBucket: 'biddingapp-2b035.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05ClCjTI36buhWFV-zVB1LIEpyj2m7ao',
    appId: '1:998569864600:ios:47a213fff1d364891c8fed',
    messagingSenderId: '998569864600',
    projectId: 'biddingapp-2b035',
    storageBucket: 'biddingapp-2b035.firebasestorage.app',
    iosBundleId: 'com.example.biddingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05ClCjTI36buhWFV-zVB1LIEpyj2m7ao',
    appId: '1:998569864600:ios:47a213fff1d364891c8fed',
    messagingSenderId: '998569864600',
    projectId: 'biddingapp-2b035',
    storageBucket: 'biddingapp-2b035.firebasestorage.app',
    iosBundleId: 'com.example.biddingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWQcc7CYIx3LSXG9Taf1COmrKxa5Njv04',
    appId: '1:998569864600:web:5a7276ebf975d9411c8fed',
    messagingSenderId: '998569864600',
    projectId: 'biddingapp-2b035',
    authDomain: 'biddingapp-2b035.firebaseapp.com',
    storageBucket: 'biddingapp-2b035.firebasestorage.app',
    measurementId: 'G-QTWJ28KKWD',
  );

}